// <auto-generated />
using DotNetProductApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831211435_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetProductApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "חלב וגבינות"
                        },
                        new
                        {
                            Id = 2,
                            Name = "טואלטיקה"
                        },
                        new
                        {
                            Id = 3,
                            Name = "בשר"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ירקות ופירות"
                        });
                });

            modelBuilder.Entity("DotNetProductApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "קוטג",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "חלב 3%",
                            Price = 5m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "שמנת חמוצה",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "קרמים",
                            Price = 142.6m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "פרסטו ג'ל",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "טיפול וטיפוח השיער",
                            Price = 33.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "קרם צ'רידה",
                            Price = 51.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "שוקים",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "סלמון",
                            Price = 75.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Name = "בצל",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "מנגו",
                            Price = 19.40m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "אגבניות",
                            Price = 7.59m
                        });
                });

            modelBuilder.Entity("DotNetProductApi.Models.Product", b =>
                {
                    b.HasOne("DotNetProductApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DotNetProductApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
